
version: '2'
services:
  redis:
    image: redis:latest
    container_name: "redis"
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:latest
    container_name: "nsqlookupd"
    ports:
      - "4160:4160"
      - "4161:4161"
    command: ["/nsqlookupd"]

  nsqd:
    image: nsqio/nsq:latest
    container_name: "nsqd"
    depends_on:
      - nsqlookupd
    links:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    command: ["/nsqd", "--broadcast-address=127.0.0.1", "--lookupd-tcp-address=nsqlookupd:4160"]

  kafka:
    image: ches/kafka:latest
    container_name: "kafka"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - ZOOKEEPER_IP=zookeeper

  zookeeper:
    image: jplock/zookeeper:3.4.6
    container_name: "zookeeper"
    ports:
      - "2181:2181"

  nats:
    image: nats:latest
    container_name: "nats"
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"

  activemq:
    image: rmohr/activemq:latest
    container_name: "activemq"
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"

